Repository Farigh/pokeclicker-automation, pull requests merged in 2022-07, with the labels that each got.

#60 Gym: Fixup league gym achievements
  src/lib/Focus/Achievements.js
Labels: bug

#61 Loader: Don't load and run before the game is fully instantiated
  src/ComponentLoader.js
Labels: enhancement

#68 Utils.Route: Don't move the player not necessary
  src/lib/Dungeon.js
  src/lib/Focus/Achievements.js
  src/lib/Focus/Quests.js
  src/lib/Utils/Route.js
Labels: bug

#69 Shop: Add a new Shop auto buy feature
  src/Automation.js
  src/ComponentLoader.js
  src/lib/Click.js
  src/lib/Dungeon.js
  src/lib/Farm.js
  src/lib/Focus.js
  src/lib/Gym.js
  src/lib/Hatchery.js
  src/lib/Items.js
  src/lib/Menu.js
  src/lib/Shop.js
  src/lib/Underground.js
  src/lib/Utils.js
Labels: feature request

#70 Dungeon: Add some completion strategy options
  src/lib/Dungeon.js
  src/lib/Farm.js
  src/lib/Focus.js
  src/lib/Focus/Achievements.js
  src/lib/Focus/Quests.js
  src/lib/Gym.js
  src/lib/Hatchery.js
  src/lib/Items.js
  src/lib/Menu.js
  src/lib/Shop.js
Labels: enhancement

#71 Focus.Gems: Consider both gym and route
  src/lib/Focus.js
  src/lib/Focus/Quests.js
  src/lib/Utils/Gym.js
  src/lib/Utils/Route.js
Labels: enhancement

#78 Trivia: Fixup roaming pokemon info
  src/lib/Trivia.js
Labels: bug

#80 Dungeon: Fix button never re-enabling while in dungeon
  src/lib/Dungeon.js
Labels: bug

#81 Hatchery: Add Pokérus speading strategy
  Readme.md
  src/lib/Hatchery.js
  src/lib/Utils/LocalStorage.js
Labels: enhancement

#85 Desktop: Add support for Pokéclicker-Desktop
  desktop/app.asar
Labels: feature request

#94 Farm/Focus: Allow player to disable oak item loadout modification
  src/lib/Farm.js
  src/lib/Focus.js
  src/lib/Focus/Achievements.js
  src/lib/Focus/Quests.js
  src/lib/Utils/Route.js
Labels: bug, feature request

#95 Mine: Improve most efficient tool selection
  src/lib/Underground.js
Labels: enhancement

#96 Focus: Add pokeball advanced settings
  src/lib/Focus.js
  src/lib/Focus/Achievements.js
  src/lib/Focus/Quests.js
  src/lib/Shop.js
  src/lib/Trivia.js
Labels: feature request

#98 Shop: Fixup shop always being visible
  src/.vscode/settings.json
  src/lib/Farm.js
  src/lib/Focus.js
  src/lib/Shop.js
Labels: bug
