Repository Farigh/pokeclicker-automation, pull requests merged in 2022-11, with the labels that each got.

#182 BattleCafe: Add battle café panel
  src/Automation.js
  src/ComponentLoader.js
  src/lib/BattleCafe.js
  src/lib/Menu.js
  src/lib/Trivia.js
  src/lib/Utils.js
Labels: new feature

#183 Shop: Fixup item name
  src/lib/Shop.js
Labels: bug

#185 Shop: Fixup regression
  src/lib/Shop.js
Labels: bug

#189 Some improvements and bug fix
  src/lib/Focus/Achievements.js
  src/lib/Menu.js
  src/lib/Shop.js
  src/lib/Utils/Route.js
Labels: bug, enhancement

#192 Focus.Achievements: Fixup gym and dungeon quests not being selected
  src/lib/Focus/Achievements.js
Labels: bug

#193 Menu: Only inverte colors for uncaught status image
  src/lib/Menu.js
Labels: bug

#199 Fixup pokédollar typo
  src/lib/Shop.js
Labels: bug

#204 Hatchery: Add UnlockMegaEvolutions setting
  src/lib/Hatchery.js
Labels: new feature

#196 Farm: add option to harvest late when not unlocking
  Readme.md
  src/lib/Farm.js
  tst/stubs/Farming/Farming.pokeclicker.stub.js
  tst/stubs/Farming/Plot.pokeclicker.stub.js
Labels: new feature

#205 BattleFrontier: Add the battle frontier automation
  src/Automation.js
  src/ComponentLoader.js
  src/lib/BattleFrontier.js
  src/lib/Gym.js
Labels: new feature

#206 Hatchery: Fix mega evolution requirement check
  src/lib/Hatchery.js
Labels: bug
