Repository Farigh/pokeclicker-automation, pull requests merged in 2022-10, with the labels that each got.

#141 Dungeon: fixup v0.9.18 regression
  Readme.md
  src/lib/Dungeon.js
  src/lib/Farm.js
Labels: bug

#147 Dungeon: Handle multiple floor dungeons
  src/lib/Dungeon.js
Labels: bug

#148 Focus.Quests: Allow the user to disable quests
  src/lib/Focus.js
  src/lib/Focus/Quests.js
  src/lib/Menu.js
Labels: new feature

#155 Hatchery: Fixup pokerus spreading feature
  Readme.md
  src/lib/Hatchery.js
Labels: bug

#157 Focus.Quest: Use the pokéball default value from general settings
  src/lib/Focus/Quests.js
Labels: bug

#158 Loader: Allow the user to choose to disable feature by default
  Automation-UserScript.js
  src/Automation.js
  src/ComponentLoader.js
  src/lib/Focus/Quests.js
  src/lib/Menu.js
Labels: enhancement

#161 Mining: Use restore items faster for continuous mining
  src/lib/Underground.js
Labels: enhancement

#162 Mining: Add an option to automatically do all diamond-positive daily deals
  src/lib/Underground.js
Labels: new feature

#164 Mine: Automatically trigger the trade when changing options
  src/lib/Underground.js
Labels: bug, enhancement

#171 Improve Mining efficiency: Let Hammer consider revealed tiles
  src/lib/Underground.js
Labels: enhancement

#174 Trivia: Improve roamers info
  src/lib/Trivia.js
Labels: enhancement

#178 Farm: use Passho strategy to farm low rate berries
  .github/workflows/tests.yml
  src/lib/Farm.js
  src/lib/Menu.js
  tst/tests/Farm/UnlockStrategies.test.in.js
  tst/utils/farming.utils.js
Labels: enhancement
